name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: suisei-cn/actions-download-file@v1
      id: actZip
      name: Download Advanced Combat Tracker
      with:
        url: "https://github.com/owner/repository/releases/latest/download/ACTv3.zip"
        target: ACTv3
    - name: Unzip ACT release zipfile
      run: 7z x ACTv3\ACTv3.zip
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
